-- Twenty independent PostgreSQL sessions. No mocked transaction/lock.
create extension if not exists pgtap with schema extensions;
create extension if not exists dblink with schema extensions;
set search_path=public,extensions;
select no_plan();
insert into auth.users(id) values ('60000001-0000-4000-8000-000000000001');
insert into public.profiles(user_id) values ('60000001-0000-4000-8000-000000000001');
insert into public.households(id,timezone_name,timezone_revision,deletion_state) values ('60000002-0000-4000-8000-000000000001','Etc/UTC',1,'active');
insert into public.household_members values ('60000002-0000-4000-8000-000000000001','60000001-0000-4000-8000-000000000001','owner',true);
create temp table fixtures(label text,sid uuid,token bytea);
insert into fixtures select label,gen_random_uuid(),extensions.gen_random_bytes(32) from unnest(array['twenty','cancel-wins','redeem-wins','expires-waiting']) label;
insert into private.pairing_sessions(id,household_id,created_by,token_digest,expires_at)
 select sid,'60000002-0000-4000-8000-000000000001','60000001-0000-4000-8000-000000000001',token,clock_timestamp()+interval '5 minutes' from fixtures;
create function pg_temp.redeem_sql(label text) returns text language sql as $f$
 select format($query$select public.redeem_pairing(%L::uuid,%L::bytea,%L::bytea,%L::bytea,
 '{"platform":"android","os_major":16,"agent_version":"synthetic","nickname":"synthetic"}')::text$query$,
 sid,token,extensions.gen_random_bytes(32),extensions.gen_random_bytes(32)) from fixtures where fixtures.label=$1;
$f$;
create function pg_temp.waiters(n integer) returns boolean language plpgsql as $f$
begin
 for i in 1..500 loop
  perform pg_stat_clear_snapshot();
  if (select count(*) from pg_stat_activity where application_name like 'kr005_worker_%' and wait_event_type='Lock')=n then return true; end if;
  perform pg_sleep(0.01);
 end loop;
 return false;
end $f$;
select dblink_connect('gate','dbname=postgres user=supabase_admin host=/var/run/postgresql application_name=kr005_gate');
select dblink_exec('gate','begin');
select count(*) from dblink('gate',format('select id::text from private.pairing_sessions where id=%L for update',(select sid from fixtures where label='twenty'))) t(id text);
create temp table results(worker integer,result jsonb);
select dblink_connect('w1','dbname=postgres user=supabase_admin host=/var/run/postgresql application_name=kr005_worker_1');
select dblink_exec('w1','set role service_role');
select dblink_exec('w1', 'set statement_timeout=30000');
select is(dblink_send_query('w1',pg_temp.redeem_sql('twenty')),1,'redemption worker 1 dispatched');
select dblink_connect('w2','dbname=postgres user=supabase_admin host=/var/run/postgresql application_name=kr005_worker_2');
select dblink_exec('w2','set role service_role');
select dblink_exec('w2', 'set statement_timeout=30000');
select is(dblink_send_query('w2',pg_temp.redeem_sql('twenty')),1,'redemption worker 2 dispatched');
select dblink_connect('w3','dbname=postgres user=supabase_admin host=/var/run/postgresql application_name=kr005_worker_3');
select dblink_exec('w3','set role service_role');
select dblink_exec('w3', 'set statement_timeout=30000');
select is(dblink_send_query('w3',pg_temp.redeem_sql('twenty')),1,'redemption worker 3 dispatched');
select dblink_connect('w4','dbname=postgres user=supabase_admin host=/var/run/postgresql application_name=kr005_worker_4');
select dblink_exec('w4','set role service_role');
select dblink_exec('w4', 'set statement_timeout=30000');
select is(dblink_send_query('w4',pg_temp.redeem_sql('twenty')),1,'redemption worker 4 dispatched');
select dblink_connect('w5','dbname=postgres user=supabase_admin host=/var/run/postgresql application_name=kr005_worker_5');
select dblink_exec('w5','set role service_role');
select dblink_exec('w5', 'set statement_timeout=30000');
select is(dblink_send_query('w5',pg_temp.redeem_sql('twenty')),1,'redemption worker 5 dispatched');
select dblink_connect('w6','dbname=postgres user=supabase_admin host=/var/run/postgresql application_name=kr005_worker_6');
select dblink_exec('w6','set role service_role');
select dblink_exec('w6', 'set statement_timeout=30000');
select is(dblink_send_query('w6',pg_temp.redeem_sql('twenty')),1,'redemption worker 6 dispatched');
select dblink_connect('w7','dbname=postgres user=supabase_admin host=/var/run/postgresql application_name=kr005_worker_7');
select dblink_exec('w7','set role service_role');
select dblink_exec('w7', 'set statement_timeout=30000');
select is(dblink_send_query('w7',pg_temp.redeem_sql('twenty')),1,'redemption worker 7 dispatched');
select dblink_connect('w8','dbname=postgres user=supabase_admin host=/var/run/postgresql application_name=kr005_worker_8');
select dblink_exec('w8','set role service_role');
select dblink_exec('w8', 'set statement_timeout=30000');
select is(dblink_send_query('w8',pg_temp.redeem_sql('twenty')),1,'redemption worker 8 dispatched');
select dblink_connect('w9','dbname=postgres user=supabase_admin host=/var/run/postgresql application_name=kr005_worker_9');
select dblink_exec('w9','set role service_role');
select dblink_exec('w9', 'set statement_timeout=30000');
select is(dblink_send_query('w9',pg_temp.redeem_sql('twenty')),1,'redemption worker 9 dispatched');
select dblink_connect('w10','dbname=postgres user=supabase_admin host=/var/run/postgresql application_name=kr005_worker_10');
select dblink_exec('w10','set role service_role');
select dblink_exec('w10', 'set statement_timeout=30000');
select is(dblink_send_query('w10',pg_temp.redeem_sql('twenty')),1,'redemption worker 10 dispatched');
select dblink_connect('w11','dbname=postgres user=supabase_admin host=/var/run/postgresql application_name=kr005_worker_11');
select dblink_exec('w11','set role service_role');
select dblink_exec('w11', 'set statement_timeout=30000');
select is(dblink_send_query('w11',pg_temp.redeem_sql('twenty')),1,'redemption worker 11 dispatched');
select dblink_connect('w12','dbname=postgres user=supabase_admin host=/var/run/postgresql application_name=kr005_worker_12');
select dblink_exec('w12','set role service_role');
select dblink_exec('w12', 'set statement_timeout=30000');
select is(dblink_send_query('w12',pg_temp.redeem_sql('twenty')),1,'redemption worker 12 dispatched');
select dblink_connect('w13','dbname=postgres user=supabase_admin host=/var/run/postgresql application_name=kr005_worker_13');
select dblink_exec('w13','set role service_role');
select dblink_exec('w13', 'set statement_timeout=30000');
select is(dblink_send_query('w13',pg_temp.redeem_sql('twenty')),1,'redemption worker 13 dispatched');
select dblink_connect('w14','dbname=postgres user=supabase_admin host=/var/run/postgresql application_name=kr005_worker_14');
select dblink_exec('w14','set role service_role');
select dblink_exec('w14', 'set statement_timeout=30000');
select is(dblink_send_query('w14',pg_temp.redeem_sql('twenty')),1,'redemption worker 14 dispatched');
select dblink_connect('w15','dbname=postgres user=supabase_admin host=/var/run/postgresql application_name=kr005_worker_15');
select dblink_exec('w15','set role service_role');
select dblink_exec('w15', 'set statement_timeout=30000');
select is(dblink_send_query('w15',pg_temp.redeem_sql('twenty')),1,'redemption worker 15 dispatched');
select dblink_connect('w16','dbname=postgres user=supabase_admin host=/var/run/postgresql application_name=kr005_worker_16');
select dblink_exec('w16','set role service_role');
select dblink_exec('w16', 'set statement_timeout=30000');
select is(dblink_send_query('w16',pg_temp.redeem_sql('twenty')),1,'redemption worker 16 dispatched');
select dblink_connect('w17','dbname=postgres user=supabase_admin host=/var/run/postgresql application_name=kr005_worker_17');
select dblink_exec('w17','set role service_role');
select dblink_exec('w17', 'set statement_timeout=30000');
select is(dblink_send_query('w17',pg_temp.redeem_sql('twenty')),1,'redemption worker 17 dispatched');
select dblink_connect('w18','dbname=postgres user=supabase_admin host=/var/run/postgresql application_name=kr005_worker_18');
select dblink_exec('w18','set role service_role');
select dblink_exec('w18', 'set statement_timeout=30000');
select is(dblink_send_query('w18',pg_temp.redeem_sql('twenty')),1,'redemption worker 18 dispatched');
select dblink_connect('w19','dbname=postgres user=supabase_admin host=/var/run/postgresql application_name=kr005_worker_19');
select dblink_exec('w19','set role service_role');
select dblink_exec('w19', 'set statement_timeout=30000');
select is(dblink_send_query('w19',pg_temp.redeem_sql('twenty')),1,'redemption worker 19 dispatched');
select dblink_connect('w20','dbname=postgres user=supabase_admin host=/var/run/postgresql application_name=kr005_worker_20');
select dblink_exec('w20','set role service_role');
select dblink_exec('w20', 'set statement_timeout=30000');
select is(dblink_send_query('w20',pg_temp.redeem_sql('twenty')),1,'redemption worker 20 dispatched');
select ok(pg_temp.waiters(20),'all twenty real sessions simultaneously blocked on challenge');
select dblink_exec('gate','commit');
insert into results select 1,result::jsonb from dblink_get_result('w1') t(result text);
select count(*) from dblink_get_result('w1') t(result text);
insert into results select 2,result::jsonb from dblink_get_result('w2') t(result text);
select count(*) from dblink_get_result('w2') t(result text);
insert into results select 3,result::jsonb from dblink_get_result('w3') t(result text);
select count(*) from dblink_get_result('w3') t(result text);
insert into results select 4,result::jsonb from dblink_get_result('w4') t(result text);
select count(*) from dblink_get_result('w4') t(result text);
insert into results select 5,result::jsonb from dblink_get_result('w5') t(result text);
select count(*) from dblink_get_result('w5') t(result text);
insert into results select 6,result::jsonb from dblink_get_result('w6') t(result text);
select count(*) from dblink_get_result('w6') t(result text);
insert into results select 7,result::jsonb from dblink_get_result('w7') t(result text);
select count(*) from dblink_get_result('w7') t(result text);
insert into results select 8,result::jsonb from dblink_get_result('w8') t(result text);
select count(*) from dblink_get_result('w8') t(result text);
insert into results select 9,result::jsonb from dblink_get_result('w9') t(result text);
select count(*) from dblink_get_result('w9') t(result text);
insert into results select 10,result::jsonb from dblink_get_result('w10') t(result text);
select count(*) from dblink_get_result('w10') t(result text);
insert into results select 11,result::jsonb from dblink_get_result('w11') t(result text);
select count(*) from dblink_get_result('w11') t(result text);
insert into results select 12,result::jsonb from dblink_get_result('w12') t(result text);
select count(*) from dblink_get_result('w12') t(result text);
insert into results select 13,result::jsonb from dblink_get_result('w13') t(result text);
select count(*) from dblink_get_result('w13') t(result text);
insert into results select 14,result::jsonb from dblink_get_result('w14') t(result text);
select count(*) from dblink_get_result('w14') t(result text);
insert into results select 15,result::jsonb from dblink_get_result('w15') t(result text);
select count(*) from dblink_get_result('w15') t(result text);
insert into results select 16,result::jsonb from dblink_get_result('w16') t(result text);
select count(*) from dblink_get_result('w16') t(result text);
insert into results select 17,result::jsonb from dblink_get_result('w17') t(result text);
select count(*) from dblink_get_result('w17') t(result text);
insert into results select 18,result::jsonb from dblink_get_result('w18') t(result text);
select count(*) from dblink_get_result('w18') t(result text);
insert into results select 19,result::jsonb from dblink_get_result('w19') t(result text);
select count(*) from dblink_get_result('w19') t(result text);
insert into results select 20,result::jsonb from dblink_get_result('w20') t(result text);
select count(*) from dblink_get_result('w20') t(result text);
select is((select count(*) from results where result->>'result'='REDEEMED'),1::bigint,'twenty attempts: exactly one winner');
select is((select count(*) from results where result->>'result'='DENIED'),19::bigint,'twenty attempts: nineteen denied');
select is((select count(*) from public.devices where household_id='60000002-0000-4000-8000-000000000001'),1::bigint,'twenty attempts: exactly one device');
select is((select count(*) from private.device_credentials c join public.devices d on c.device_id=d.id where d.household_id='60000002-0000-4000-8000-000000000001'),1::bigint,'twenty attempts: exactly one credential');
-- Cancellation wins, redemption is really waiting until cancellation commits.
select dblink_exec('gate','begin');
select dblink_exec('gate','set local role authenticated');
select dblink_exec('gate',$q$set local "request.jwt.claim.sub"='60000001-0000-4000-8000-000000000001'$q$);
select is((select (r::jsonb)->>'result' from dblink('gate',format('select public.finish_pairing(%L)::text',(select sid from fixtures where label='cancel-wins'))) t(r text)),'CANCELLED','cancel winner inside open transaction');
select is(dblink_send_query('w1',pg_temp.redeem_sql('cancel-wins')),1,'redemption overlaps cancellation');
select ok(pg_temp.waiters(1),'redemption waits for cancellation');
select dblink_exec('gate','commit');
select is((select (r::jsonb)->>'result' from dblink_get_result('w1') t(r text)),'DENIED','cancel commit prevents redemption');
select count(*) from dblink_get_result('w1') t(r text);
-- Redemption wins, cancelled request observes consumed identity, cannot replay secret.
select dblink_exec('gate','begin');
select dblink_exec('gate','set local role service_role');
select is((select (r::jsonb)->>'result' from dblink('gate',pg_temp.redeem_sql('redeem-wins')) t(r text)),'REDEEMED','redemption winner inside open transaction');
select dblink_exec('w1','set role authenticated');
select dblink_exec('w1',$q$set "request.jwt.claim.sub"='60000001-0000-4000-8000-000000000001'$q$);
select is(dblink_send_query('w1',format('select public.finish_pairing(%L)::text',(select sid from fixtures where label='redeem-wins'))),1,'cancel overlaps redemption');
select ok(pg_temp.waiters(1),'cancel waits for redemption');
select dblink_exec('gate','commit');
select is((select (r::jsonb)->>'result' from dblink_get_result('w1') t(r text)),'ALREADY_REDEEMED','redemption commit requires revoke/fresh QR');
select count(*) from dblink_get_result('w1') t(r text);
-- Expiry checked after lock, even when worker transaction started while valid.
select dblink_exec('gate','begin');
select dblink_exec('gate',format($q$update private.pairing_sessions set expires_at=clock_timestamp()+interval '1 second' where id=%L$q$,(select sid from fixtures where label='expires-waiting')));
select dblink_exec('w1','set role service_role');
select is(dblink_send_query('w1',pg_temp.redeem_sql('expires-waiting')),1,'expiry worker started while session pending');
select ok(pg_temp.waiters(1),'expiry worker observed waiting');
select pg_sleep(1.1);
select dblink_exec('gate','commit');
select is((select (r::jsonb)->>'result' from dblink_get_result('w1') t(r text)),'DENIED','expired during lock wait denied using server time after lock');
select count(*) from dblink_get_result('w1') t(r text);
select dblink_disconnect('w1');
select dblink_disconnect('w2');
select dblink_disconnect('w3');
select dblink_disconnect('w4');
select dblink_disconnect('w5');
select dblink_disconnect('w6');
select dblink_disconnect('w7');
select dblink_disconnect('w8');
select dblink_disconnect('w9');
select dblink_disconnect('w10');
select dblink_disconnect('w11');
select dblink_disconnect('w12');
select dblink_disconnect('w13');
select dblink_disconnect('w14');
select dblink_disconnect('w15');
select dblink_disconnect('w16');
select dblink_disconnect('w17');
select dblink_disconnect('w18');
select dblink_disconnect('w19');
select dblink_disconnect('w20');
select dblink_disconnect('gate');
select * from finish();
